version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  fluentbit:
    image: fluent/fluent-bit:1.3
    ports:
      - "24224:24224"
    volumes:
      - $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  kibana:
    image: kibana:7.6.0
    ports:
      - "5601:5601"
